version: '3'
services:
  spark:
    #whether you want to build the docker image comment the "image" line and uncomment "build" line
    #build: docker
    image: apache/zeppelin:0.9.0
    hostname: localhost
    ports:
     - "8080:8080"
     - "4040:4040"
    environment:
     - ZEPPELIN_JAVA_OPTS=-Dcassandra.hosts=cassandra
    volumes:
    - ./data:/zeppelin/data
    - ./notebooks:/zeppelin/notebook  
    links: 
    - cassandra
    depends_on: 
    - cassandra
  cassandra:
    image: cassandra:3.11.10    
    ports:
    - "9042:9042"
  nifi:
    image: apache/nifi:1.12.1
    ports:
    - "8090:8080"
    links:
    - mosquitto
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
     - zookeeper 
  mosquitto:
    image: vimagick/mosquitto
    ports:
    - "1883:1883"
    - "8070:8080"
    - "8883:8883"
    volumes:
    - ./mqtt/mosquitto.conf:/etc/mosquitto/mosquitto.conf
    - ./mqtt/pwfile:/etc/mosquitto/pwfile
    - ./mqtt:/var/lib/mosquitto
    restart: always
